### ISSUE TITLE
Circle has edges

### ISSUE THREAD

**Issue by 12bchl** [jamesrweb/react-p5-wrapper#130]
## Expected Behavior
Circle and ellipse function should appear clean as they do inside p5 interpreter.

## Actual Behavior
Circles have 25 edges. Even with p5.smooth() applied they still look bad unfortunately. My work around is to rotate by pi/200 and draw another circle 16 times total. Ends up looking perfect after but seems a bit inefficient.

## Steps to Reproduce the Problem

1. p5.circle(x,y,d)
2. Look at screen

Great library so far aside from this. Is there some setting I'm missing or maybe an older version had better circles?

Package Version: 3.0.2

**Comment by jamesrweb** [comment]
@12bchl Please provide your sketch file for review.

Since we just extend `P5` for some types and don't alter or overwrite anything `P5` exports, if there is an issue, it must be in your sketch itself.

This library makes no changes to `P5` and only allows you a way to cleanly and efficiently render `P5` sketches via React.

**Comment by 12bchl** [comment]
Yeah it doesn't really make sense to me either. It always makes a 25-a-gon not a circle. Running node 16.10 and latest p5-wrapper. In a p5 interpreter it looks perfectly fine of course.

![image](https://user-images.githubusercontent.com/35347960/140735013-3f370b2f-b0c7-42ef-a874-d307b791f344.png)

```
export function sketch_test3(p5) {
  
    let i = 0; // Angle in pi rads
    let r = 100; // length of drawing edges
    let w = 400; // width of canvas
  
  p5.setup = () => p5.createCanvas(w, w, p5.WEBGL);
  
  p5.updateWithProps = props => {
      if (props.r || props.i) {
        r = props.r;
        i = props.i;
      }
  };
  
  p5.draw = () => {
      p5.smooth()
      let diam = 2*r
      p5.fill(0)
      p5.circle(0,0,diam)
      p5.fill(255)
      p5.circle(0,0,diam*0.8)
  }
}
```

**Comment by jamesrweb** [comment]
What is the pixel density of your display? Maybe you need to set that via [p5.pixelDensity](https://p5js.org/reference/#/p5/pixelDensity) for example.

I will close this ticket now since it is a  `p5` issue and not one with this library. I would recommend opening an issue on the main repository of `p5.js` if the pixel density doesn't resolve the issue because we don't change `p5` behaviour here and so any solution (if any is even needed), needs fixed upstream either way.

**Comment by yevdyko** [comment]
@12bchl I wonder if you need to use WEBGL mode in your sketch because without it the circles will be smoother?

![image](https://user-images.githubusercontent.com/13007925/141387457-19b588b5-efa0-4149-9488-88a706afd265.png)

**Comment by 12bchl** [comment]
Thank you for the replies! Indeed WEBGL was the culprit. Although for some reason it's still a tad cleaner to overlay 16 circles on top of each other XD
