### ISSUE TITLE
CRA live update not working

### ISSUE THREAD

**Issue by dcsan** [jamesrweb/react-p5-wrapper#132]
when i make a change to the sketch component and save, the app doesn't show any changes or even trigger a refresh

if i edit the parent component and save, everything updates (including the sketch component)

Is this cos the p5 function you create is somehow caching between live reloads or using refs?

I messed around with passing a timestamp in as a prop each time from the parent, but no luck.

this is using vanilla create-react-app and react 17.0.2

## parent page
```tsx
import { Link as LinkRoute } from "react-router-dom";
import {
    Box,
    Text,
    Button,
    Heading,
} from "@chakra-ui/react";
import { useParams, useRouteMatch } from 'react-router-dom'
// import P5Wrapper from 'react-p5-wrapper';
import { ReactP5Wrapper } from "react-p5-wrapper";


import Hanabi from '../Hanabi/Hanabi'

const ViewPage = () => {

    const params = useParams();
    console.log('params', params)

    // @ts-ignore
    const tokenId = params ? params.tokenId : 0

    const config = {
        tokenId,
        stamp: Date.now()
    }

    return (
        <Box p={5}>
            <Text>tokenId: {tokenId}</Text>
            <Text>version: {1}</Text>
            <Text>stamp: {config.stamp}</Text>
            <ReactP5Wrapper sketch={Hanabi} config={config} />
        </Box>
    )
}

export default ViewPage
```

## sketch component

```tsx
import { P5Instance } from "react-p5-wrapper";

const Hanabi = (p5: P5Instance) => {

    let message = 'start'
    const version = 'v2'
    let count = 0
    let cfg = {
        tokenId: 0,
        stamp: 0
    }

    p5.setup = () => {
        p5.createCanvas(window.innerWidth, window.innerHeight);
        p5.background(0);
        p5.stroke(255);
        p5.strokeWeight(2);
    }

    p5.updateWithProps = props => {
        // gets called once?
        cfg = props.config // make accessible to the sketch
    };

    p5.draw = () => {
        count++
        console.log('draw')
        p5.background('green')
        p5.fill('white')
        // error props are not available in draw loop
        message = `v${version} ${cfg.tokenId} | ${count}`
        p5.textSize(32)
        p5.text(cfg.stamp, 100, 50)
        p5.text(message, 100, 100)
    }

}

export default Hanabi
```

**Comment by jamesrweb** [comment]
The `updateWithProps` function is only called when the props passed to the `P5Wrapper` component are changed. If the props don't change, [it won't do an unnecessary re-render](https://github.com/P5-wrapper/react/blob/91d3669e9a18a4f295250798550ae79c77f781e3/src/index.tsx#L44) since the props are the same.

The only `ref` that we use [is one which P5 itself needs](https://github.com/P5-wrapper/react/blob/91d3669e9a18a4f295250798550ae79c77f781e3/src/index.tsx#L31) to render the sketch into the container. It doesn't affect anything for the user, it is purely internal.

**Comment by dcsan** [comment]
thanks for the quick reply. The update with props was just an extra thing I was trying to work out with this lib.

The main problem is I don't get auto-updates, so I have to go to the browser and ctrl-R every time i change code. Is this expected behavior, a consequence of `useRef` ?

**Comment by jamesrweb** [comment]
No, it is simply that if the parent component doesn't pass "different" props, then it won't re-render.

**Comment by jamesrweb** [comment]
@yevdyko what do you think about this topic?

**Comment by dcsan** [comment]
right, so that's why i was passing a timestamp through which is different each time. I also had a version stamp I was updating. Again, the parent page will change - the wrapper _around_ the component but nothing, code or render changes inside the p5 component. updating any code in the p5 area of my project will trigger the page to reload - CRA is reloading - but the P5 rendering code remains unchanged.

**Comment by jamesrweb** [comment]
> right, so that's why i was passing a timestamp through which is different each time. I also had a version stamp I was updating. Again, the parent page will change - the wrapper _around_ the component but nothing, code or render changes inside the p5 component. updating any code in the p5 area of my project will trigger the page to reload - CRA is reloading - but the P5 rendering code remains unchanged.

I will test later, doesn't sound right to me. 🤔

**Comment by dcsan** [comment]
I did a hack for now basically deleting a p5 canvas element manually, since p5 (for now!) always names it `defaultCanvas0` 
This feels like a hack to me, just deleting the element on every re-render, but i don't really have a better solution. If nothing changed then I guess this is a big waste of dom-diffing, but i don't really have much else on the page that changes...

I'm wondering what the shortcomings of this are over your approach, eg `instance.remove()`.

https://github.com/P5-wrapper/react/blob/master/src/index.tsx#L39

i see you have something isomorphic, have you tested this with server-side rendering too?

```
        // this is a hack to delete the previous p5 canvas instance for hot reloading
        let old = document.getElementById('defaultCanvas0')
        if (old) {
            console.log('removed')
            old.remove()
        }

```


```
        // another way of doing it if used 

            cnv = pin.createCanvas(size.x, size.y);
            cnv.parent('art-frame')

        // let frame = document.getElementById("art-frame");
        // while (frame?.firstChild) {
        //     frame.removeChild(frame.firstChild);
        // }

```

**Comment by jamesrweb** [comment]
Server side rendering has test coverage in the CI for all possible server rendering capabilities of react, you can check inside the `tests` folder for them.

The `effect` which calls `instance?.remove()` has to do this, it is how the sketch is updated with new information since `p5` doesn't support dynamic re-rendering and this package solves that problem.

I tested with the following code to replicate an update to the `config` object and everything worked as expected, my suspicion is that you have issues in your next js code, this library isn't having issues as far as I can see from testing in this regard. If the value doesn't change, the component won't re-render, if it does, it will.

```ts
import * as React from 'react'
import './App.css'
import { ReactP5Wrapper, P5Instance } from "react-p5-wrapper";

const Hanabi = (p5: P5Instance) => {

    let message = 'start'
    const version = 'v2'
    let count = 0
    let cfg = {
        tokenId: 0,
        stamp: 0
    }

    p5.setup = () => {
        p5.createCanvas(window.innerWidth, window.innerHeight);
        p5.background(0);
        p5.stroke(255);
        p5.strokeWeight(2);
    }

    p5.updateWithProps = props => {
        // gets called once?
        cfg = props.config // make accessible to the sketch
    };

    p5.draw = () => {
        count++
        console.log('draw')
        p5.background('green')
        p5.fill('white')
        // error props are not available in draw loop
        message = `v${version} ${cfg.tokenId} | ${count}`
        p5.textSize(32)
        p5.text(cfg.stamp, 100, 50)
        p5.text(message, 100, 100)
    }

}

export default function App() {
  const config = { tokenId: 1, stamp: 1}

  React.useEffect(() => {
    setInterval(() => config.tokenId += 1000, 2000);
  })
  
  return (
    <ReactP5Wrapper sketch={Hanabi} config={config} />
  )
}
```

Don't use hacks like the one you demonstrated as it will mess up the internals of this library and potentially break your implementation. My suspicion is that your `tokenId` constant never changes value and thus, the config doesn't change and thus the component doesn't re-render.

I will close this issue now as it isn't a library issue from what I see, if you find  something showing that it is an issue here, please re-open this issue with the new context 🙏🏻.

**Comment by dcsan** [comment]
it wasn't so much about propagating changes, it was just hot-reload on save. eg if i modify the code for the sketch, nothing updates until i ctrl-R the whole page.

pushing a timestamp through the whole pipeline (prop drilling kind of) was just a way to try to bust any caches and force a re-render. that didn't work...

**Comment by jamesrweb** [comment]
As shown in the example above, it does re-render when the props do which implies the props don't change in your app, check the config again and check how next is handling the re-render on it's side also. I see no issue here that we can action upon currently.

**Comment by dcsan** [comment]
right but if the *code* changes? should that not cause a re-render? not the data / props passed in. I modify the code, I hope not to have to toggle to the browser and reload. that's the whole issue here... sorry if that's not clear.

> when i make a change to the sketch component and save, the app doesn't show any changes or even trigger a refresh

**Comment by jamesrweb** [comment]
I'll have another look later but the sketch is a prop and if it changes, so does the rendered output so I don't see this being an issue of the library still but I'll verify again and come back with results later 👀👍🏻

**Comment by jamesrweb** [comment]
So after testing a bit, I believe that this is a create-react-app / JS module caveat. What do I mean by this?

I tried 3 different ways of using the sketch:

1. Sketch within the same file
2. Sketch exported as default
3. Sketch exported as named export

The options 2 and 3, as you described, do not update the canvas when something is changed in the sketch after loading, option 1 works as expected.

This is a create-react-app or JS itself and I assume it is because they are trying to be smart and caching the import at runtime so it doesn't reload the file multiple times with potentially conflicting results.

There is nothing I see that I can implement to solve that though in the library considering that it is a build / language implementation and not an issue here but instead with how imports and exports are working and after researching a bit, it doesn't seem to have any work arounds.

This being the case you have to either reload manually or you could pass "action functions" via the props and run those within the sketch instead. For example passing the count into the sketch and then counting up using `setState` in a callback passed from the parent which then passes the new state down, does that make sense? Either way, that's why that happens, I would raise it on the create-react-app repo to be sure it isn't a language level feature but if it is, nothing can be done.
