### ISSUE TITLE
BlendMode.REMOVE is not part of BLEND_MODE union

### ISSUE THREAD

**Issue by dbelokon** [jamesrweb/react-p5-wrapper#148]
## Expected Behavior

To call `blendMode()` with `REMOVE` value.

## Actual Behavior

Typescript reports a type error.

## Steps to Reproduce the Problem

1. In a React project with Typescript enabled, write `p5.blendMode(p5.REMOVE)`
2. When you compile, you should get a compiler error.

## Specifications

Package Version: 3.1.0

### Additional notes

One workaround is to call `blendMode()` with `REMOVE` and cast `REMOVE` with another value of the union:

```ts
p5.blendMode(p5.REMOVE as typeof p5.ADD);
```

**Comment by jamesrweb** [comment]
Hi @dbelokon, we don't change anything to do with `p5` itself and so the issue is most certainly not introduced in this repository.

However, I have taken a look and found [this open issue](https://github.com/processing/p5.js/issues/5616) in the p5.js repository. Once it is resolved there and published to the `@types/p5` repository, it will be automatically resolved for users of this library.

We never have and never will overwrite or alter _any_ areas of the `p5` API and thus any fixes must be applied there.

I hope this helped and that they release a fix soon for this 😄✌🏻!

**Comment by dbelokon** [comment]
Oh I see. 

Thank you so much!!😁

**Comment by jamesrweb** [comment]
> Oh I see. 
> 
> 
> 
> Thank you so much!!😁

You're welcome, thanks for raising the issue as it's good to know these things exist for users and all the best as you continue using the wrapper!
