### ISSUE TITLE
Latest commits not in the npm registry

### ISSUE THREAD

**Issue by ScarpMetal** [jamesrweb/react-p5-wrapper#286]
## Expected Behavior
After every new commit to the `master` branch, a new version of the library is published to the npm registry. This is done via the CD.yml GitHub Action.

## Actual Behavior
CD.yml action skips publishing to npm registry, likely because the version number is not being incremented after every commit. 

Link to latest action: https://github.com/P5-wrapper/react/actions/runs/6848858980/job/18619860018#step:4:8

## Steps to Reproduce the Problem
N/A

## Specifications

Package Version: 4.2.0

**Comment by jamesrweb** [comment]
@ScarpMetal you're absolutely correct. The releases don't run unless the package version is manually incremented. This is on purpose, incase of some kind of issue in the automation pipeline that's not caught.

I'll make a new release on Sunday. If @yevdyko is finished with issue #282 by then, I'll release it as a minor update OR otherwise I'll release the current repo state as a patch update.

I suppose we could remove this requirement to manually bump the version in future. I'm not sure how to automate the version bumps in a semantically correct way while maintaining the quality of releases so that nothing accidentally breaks while myself or @yevdyko are asleep or something though 😂😅.

Happy for suggestions or PRs 😉👍🏻

**Comment by ScarpMetal** [comment]
@jamesrweb I know the [npm-version](https://docs.npmjs.com/cli/v8/commands/npm-version) command allows you to easily bump versions. Not sure if you would work that into your workflow as a pre-commit hook or as an auto-commit, but I'll leave that discussion up to the regular contributors as I don't have context for this. Manual version bumps semi-frequently are fine too :)

**Comment by karimStekelenburg** [comment]
For fully automatic SemVer-based releasing, you might want to give this a look https://github.com/semantic-release/semantic-release

**Comment by jamesrweb** [comment]
@ScarpMetal @karimStekelenburg would any of you be open to creating a PR with a suggested direction if this is something you see value in?

**Comment by jamesrweb** [comment]
v4.3.0 is now released, please create a new issue for anything noticed.
