### ISSUE TITLE
Is this package supported in React Native?

### ISSUE THREAD

**Issue by jtvargas** [jamesrweb/react-p5-wrapper#369]
## Expected Behavior

Like the title says, I want to know if this package is supported in React Native if that the case what steps I need to take to make it possible?

## Actual Behavior

N/A

## Steps to Reproduce the Problem

N/A

## Specifications

Package Version: Latest

**Comment by jamesrweb** [comment]
As mentioned in #124, it's not a focus for this library since we target the browser. You could use this library as is via a web view though, since you need the window object to be available for p5 to run at all and maybe there's extra unforeseen overhead also such as browser APIs which need to be available for p5 too. That's out of the scope of this library to document however.
